seed: 42

data:
  dataset:
#    image_path: '/home/ge29pim/spectral-dexa-segmentation/new_data/pydele_volumes/'
    image_path: 'G:\Code\ba\thesis-gui\segmentation\inputs\'
    mask_path: '/home/ge29pim/spectral-dexa-segmentation/new_data/pydele_masks/'

  loader:
    batch_size: 8
    num_workers: 12

trainer:
  max_epochs: 250
  gpus: 1

optimizer:
  lr: 0.0003

eval: True
save_path: './outputs/'